services:

  core-db:
    image: postgres:15-alpine
    container_name: core-db
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  bank_app:
    build:
      context: ./bank_app
      dockerfile: Dockerfile
    container_name: bank_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/banking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - core-db